// GENERATED by scripts/sync-abi.mjs from contracts/. Do not edit by hand.
import type { Abi } from 'starknet';

export const EXECUTION_VERIFIER_ABI = [
  {
    "type": "impl",
    "name": "ExecutionVerifierImpl",
    "interface_name": "intentproof::interfaces::IExecutionVerifier"
  },
  {
    "type": "enum",
    "name": "core::bool",
    "variants": [
      {
        "name": "False",
        "type": "()"
      },
      {
        "name": "True",
        "type": "()"
      }
    ]
  },
  {
    "type": "struct",
    "name": "intentproof::types::VerificationResult",
    "members": [
      {
        "name": "verified",
        "type": "core::bool"
      },
      {
        "name": "failure_code",
        "type": "core::felt252"
      }
    ]
  },
  {
    "type": "interface",
    "name": "intentproof::interfaces::IExecutionVerifier",
    "items": [
      {
        "type": "function",
        "name": "registry",
        "inputs": [],
        "outputs": [
          {
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "verify",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "receipt_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::VerificationResult"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "verify_commitment",
        "inputs": [
          {
            "name": "canonical_chunks",
            "type": "core::array::Array::<core::felt252>"
          },
          {
            "name": "expected_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "core::bool"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "verify_receipt",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "receipt_chunks",
            "type": "core::array::Array::<core::felt252>"
          },
          {
            "name": "receipt_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::VerificationResult"
          }
        ],
        "state_mutability": "view"
      }
    ]
  },
  {
    "type": "constructor",
    "name": "constructor",
    "inputs": [
      {
        "name": "registry",
        "type": "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::execution_verifier::ExecutionVerifier::Event",
    "kind": "enum",
    "variants": []
  }
] as const satisfies Abi;
