// GENERATED by scripts/sync-abi.mjs from contracts/. Do not edit by hand.
import type { Abi } from 'starknet';

export const INTENT_REGISTRY_ABI = [
  {
    "type": "impl",
    "name": "IntentRegistryImpl",
    "interface_name": "intentproof::interfaces::IIntentRegistry"
  },
  {
    "type": "struct",
    "name": "intentproof::types::RegisterIntentParams",
    "members": [
      {
        "name": "intent_hash",
        "type": "core::felt252"
      },
      {
        "name": "version",
        "type": "core::integer::u32"
      },
      {
        "name": "expires_at",
        "type": "core::integer::u64"
      },
      {
        "name": "max_tx_value_usd_cents",
        "type": "core::integer::u128"
      },
      {
        "name": "max_daily_spend_usd_cents",
        "type": "core::integer::u128"
      },
      {
        "name": "agent",
        "type": "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    "type": "enum",
    "name": "core::bool",
    "variants": [
      {
        "name": "False",
        "type": "()"
      },
      {
        "name": "True",
        "type": "()"
      }
    ]
  },
  {
    "type": "struct",
    "name": "intentproof::types::VerificationResult",
    "members": [
      {
        "name": "verified",
        "type": "core::bool"
      },
      {
        "name": "failure_code",
        "type": "core::felt252"
      }
    ]
  },
  {
    "type": "struct",
    "name": "intentproof::types::Intent",
    "members": [
      {
        "name": "id",
        "type": "core::integer::u64"
      },
      {
        "name": "intent_hash",
        "type": "core::felt252"
      },
      {
        "name": "creator",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "version",
        "type": "core::integer::u32"
      },
      {
        "name": "created_at",
        "type": "core::integer::u64"
      },
      {
        "name": "expires_at",
        "type": "core::integer::u64"
      },
      {
        "name": "revoked_at",
        "type": "core::integer::u64"
      },
      {
        "name": "max_tx_value_usd_cents",
        "type": "core::integer::u128"
      },
      {
        "name": "max_daily_spend_usd_cents",
        "type": "core::integer::u128"
      },
      {
        "name": "execution_count",
        "type": "core::integer::u64"
      },
      {
        "name": "total_spend_usd_cents",
        "type": "core::integer::u128"
      },
      {
        "name": "exists",
        "type": "core::bool"
      }
    ]
  },
  {
    "type": "enum",
    "name": "intentproof::types::IntentStatus",
    "variants": [
      {
        "name": "Unknown",
        "type": "()"
      },
      {
        "name": "Active",
        "type": "()"
      },
      {
        "name": "Revoked",
        "type": "()"
      },
      {
        "name": "Expired",
        "type": "()"
      }
    ]
  },
  {
    "type": "struct",
    "name": "intentproof::types::ExecutionRecord",
    "members": [
      {
        "name": "intent_hash",
        "type": "core::felt252"
      },
      {
        "name": "receipt_hash",
        "type": "core::felt252"
      },
      {
        "name": "action_hash",
        "type": "core::felt252"
      },
      {
        "name": "agent",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "value_usd_cents",
        "type": "core::integer::u128"
      },
      {
        "name": "recorded_at",
        "type": "core::integer::u64"
      },
      {
        "name": "sequence",
        "type": "core::integer::u64"
      },
      {
        "name": "exists",
        "type": "core::bool"
      }
    ]
  },
  {
    "type": "interface",
    "name": "intentproof::interfaces::IIntentRegistry",
    "items": [
      {
        "type": "function",
        "name": "register_intent",
        "inputs": [
          {
            "name": "params",
            "type": "intentproof::types::RegisterIntentParams"
          }
        ],
        "outputs": [
          {
            "type": "core::integer::u64"
          }
        ],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "register_intent_from_canonical",
        "inputs": [
          {
            "name": "canonical_chunks",
            "type": "core::array::Array::<core::felt252>"
          },
          {
            "name": "params",
            "type": "intentproof::types::RegisterIntentParams"
          }
        ],
        "outputs": [
          {
            "type": "core::integer::u64"
          }
        ],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "revoke_intent",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "authorize_agent",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "agent",
            "type": "core::starknet::contract_address::ContractAddress"
          },
          {
            "name": "authorized",
            "type": "core::bool"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "record_execution",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "receipt_hash",
            "type": "core::felt252"
          },
          {
            "name": "action_hash",
            "type": "core::felt252"
          },
          {
            "name": "value_usd_cents",
            "type": "core::integer::u128"
          }
        ],
        "outputs": [
          {
            "type": "core::integer::u64"
          }
        ],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "attest_execution",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "receipt_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::VerificationResult"
          }
        ],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "set_paused",
        "inputs": [
          {
            "name": "paused",
            "type": "core::bool"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "get_intent",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::Intent"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_intent_by_id",
        "inputs": [
          {
            "name": "intent_id",
            "type": "core::integer::u64"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::Intent"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_intent_hash_by_id",
        "inputs": [
          {
            "name": "intent_id",
            "type": "core::integer::u64"
          }
        ],
        "outputs": [
          {
            "type": "core::felt252"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "is_intent_active",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "core::bool"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_intent_status",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::IntentStatus"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_execution",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "receipt_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::ExecutionRecord"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_execution_by_index",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "index",
            "type": "core::integer::u64"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::ExecutionRecord"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "verify_execution",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "receipt_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "intentproof::types::VerificationResult"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "intent_count",
        "inputs": [],
        "outputs": [
          {
            "type": "core::integer::u64"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "execution_count",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          }
        ],
        "outputs": [
          {
            "type": "core::integer::u64"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "daily_spend",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "day",
            "type": "core::integer::u64"
          }
        ],
        "outputs": [
          {
            "type": "core::integer::u128"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "is_agent_authorized",
        "inputs": [
          {
            "name": "intent_hash",
            "type": "core::felt252"
          },
          {
            "name": "agent",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [
          {
            "type": "core::bool"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "is_paused",
        "inputs": [],
        "outputs": [
          {
            "type": "core::bool"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "compute_policy_hash",
        "inputs": [
          {
            "name": "canonical_chunks",
            "type": "core::array::Array::<core::felt252>"
          }
        ],
        "outputs": [
          {
            "type": "core::felt252"
          }
        ],
        "state_mutability": "view"
      }
    ]
  },
  {
    "type": "impl",
    "name": "OwnableImpl",
    "interface_name": "intentproof::components::ownable::IOwnable"
  },
  {
    "type": "interface",
    "name": "intentproof::components::ownable::IOwnable",
    "items": [
      {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [
          {
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "pending_owner",
        "inputs": [],
        "outputs": [
          {
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "transfer_ownership",
        "inputs": [
          {
            "name": "new_owner",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "accept_ownership",
        "inputs": [],
        "outputs": [],
        "state_mutability": "external"
      },
      {
        "type": "function",
        "name": "renounce_ownership",
        "inputs": [],
        "outputs": [],
        "state_mutability": "external"
      }
    ]
  },
  {
    "type": "constructor",
    "name": "constructor",
    "inputs": [
      {
        "name": "owner",
        "type": "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::intent_registry::IntentRegistry::IntentCreated",
    "kind": "struct",
    "members": [
      {
        "name": "intent_hash",
        "type": "core::felt252",
        "kind": "key"
      },
      {
        "name": "creator",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "intent_id",
        "type": "core::integer::u64",
        "kind": "data"
      },
      {
        "name": "version",
        "type": "core::integer::u32",
        "kind": "data"
      },
      {
        "name": "created_at",
        "type": "core::integer::u64",
        "kind": "data"
      },
      {
        "name": "expires_at",
        "type": "core::integer::u64",
        "kind": "data"
      },
      {
        "name": "max_tx_value_usd_cents",
        "type": "core::integer::u128",
        "kind": "data"
      },
      {
        "name": "max_daily_spend_usd_cents",
        "type": "core::integer::u128",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::intent_registry::IntentRegistry::IntentRevoked",
    "kind": "struct",
    "members": [
      {
        "name": "intent_hash",
        "type": "core::felt252",
        "kind": "key"
      },
      {
        "name": "revoked_by",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "revoked_at",
        "type": "core::integer::u64",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::intent_registry::IntentRegistry::AgentAuthorizationChanged",
    "kind": "struct",
    "members": [
      {
        "name": "intent_hash",
        "type": "core::felt252",
        "kind": "key"
      },
      {
        "name": "agent",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "authorized",
        "type": "core::bool",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::intent_registry::IntentRegistry::ExecutionRecorded",
    "kind": "struct",
    "members": [
      {
        "name": "intent_hash",
        "type": "core::felt252",
        "kind": "key"
      },
      {
        "name": "receipt_hash",
        "type": "core::felt252",
        "kind": "key"
      },
      {
        "name": "agent",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "action_hash",
        "type": "core::felt252",
        "kind": "data"
      },
      {
        "name": "value_usd_cents",
        "type": "core::integer::u128",
        "kind": "data"
      },
      {
        "name": "sequence",
        "type": "core::integer::u64",
        "kind": "data"
      },
      {
        "name": "recorded_at",
        "type": "core::integer::u64",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::intent_registry::IntentRegistry::ExecutionVerified",
    "kind": "struct",
    "members": [
      {
        "name": "intent_hash",
        "type": "core::felt252",
        "kind": "key"
      },
      {
        "name": "receipt_hash",
        "type": "core::felt252",
        "kind": "key"
      },
      {
        "name": "verifier",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "verified",
        "type": "core::bool",
        "kind": "data"
      },
      {
        "name": "failure_code",
        "type": "core::felt252",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::intent_registry::IntentRegistry::PausedSet",
    "kind": "struct",
    "members": [
      {
        "name": "paused",
        "type": "core::bool",
        "kind": "data"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::components::ownable::OwnableComponent::OwnershipTransferStarted",
    "kind": "struct",
    "members": [
      {
        "name": "previous_owner",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "new_owner",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::components::ownable::OwnableComponent::OwnershipTransferred",
    "kind": "struct",
    "members": [
      {
        "name": "previous_owner",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      },
      {
        "name": "new_owner",
        "type": "core::starknet::contract_address::ContractAddress",
        "kind": "key"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::components::ownable::OwnableComponent::Event",
    "kind": "enum",
    "variants": [
      {
        "name": "OwnershipTransferStarted",
        "type": "intentproof::components::ownable::OwnableComponent::OwnershipTransferStarted",
        "kind": "nested"
      },
      {
        "name": "OwnershipTransferred",
        "type": "intentproof::components::ownable::OwnableComponent::OwnershipTransferred",
        "kind": "nested"
      }
    ]
  },
  {
    "type": "event",
    "name": "intentproof::intent_registry::IntentRegistry::Event",
    "kind": "enum",
    "variants": [
      {
        "name": "IntentCreated",
        "type": "intentproof::intent_registry::IntentRegistry::IntentCreated",
        "kind": "nested"
      },
      {
        "name": "IntentRevoked",
        "type": "intentproof::intent_registry::IntentRegistry::IntentRevoked",
        "kind": "nested"
      },
      {
        "name": "AgentAuthorizationChanged",
        "type": "intentproof::intent_registry::IntentRegistry::AgentAuthorizationChanged",
        "kind": "nested"
      },
      {
        "name": "ExecutionRecorded",
        "type": "intentproof::intent_registry::IntentRegistry::ExecutionRecorded",
        "kind": "nested"
      },
      {
        "name": "ExecutionVerified",
        "type": "intentproof::intent_registry::IntentRegistry::ExecutionVerified",
        "kind": "nested"
      },
      {
        "name": "PausedSet",
        "type": "intentproof::intent_registry::IntentRegistry::PausedSet",
        "kind": "nested"
      },
      {
        "name": "OwnableEvent",
        "type": "intentproof::components::ownable::OwnableComponent::Event",
        "kind": "nested"
      }
    ]
  }
] as const satisfies Abi;
