#!/usr/bin/env node
/**
 * Copies the ABIs out of the Scarb build into a TypeScript module.
 *
 * The client cannot read `contracts/target/` at runtime — that directory does
 * not exist in a Vercel deployment — so the ABI is checked in as generated
 * source. Re-run this after any change to a contract's external interface, or
 * the client and the deployed class will silently disagree.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');
const targets = [
  ['IntentRegistry', 'intent-registry'],
  ['ExecutionVerifier', 'execution-verifier'],
];

for (const [contract, slug] of targets) {
  const source = resolve(repo, `contracts/target/dev/intentproof_${contract}.contract_class.json`);
  const artifact = JSON.parse(readFileSync(source, 'utf8'));
  const out = resolve(repo, `packages/starknet/src/abi/${slug}.ts`);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(
    out,
    `// GENERATED by scripts/sync-abi.mjs from contracts/. Do not edit by hand.\n` +
      `import type { Abi } from 'starknet';\n\n` +
      `export const ${contract.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()}_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const satisfies Abi;\n`,
  );
  console.log(`wrote ${out} (${artifact.abi.length} ABI entries)`);
}
